auto:        true
lsi:         false
port: 5000
base_url: ./
pygments:    true
markdown: rdiscount
name: manjunath kalburgi
description: personal website
url: http://kalburgimanjunath.github.io/pl/

permalink: /:categories/:title